general:
  data_autobalance: False
  print_dataset_features: True
  batch_size: 1
  extract_features: False
run:
  num_epochs : 50
  learning_rate : 0.0001
  seed: 1800
  k_fold: 5
interpretability_methods:
  saliency:
    enabled: False
    number_of_samples: 3
    sample_ids:
  LayerGradCAM:
    enabled: False
    number_of_samples: 3
    sample_ids:
    layer: 0
    assign_attribution: hard
  RISE:
    enabled: False
    number_of_samples: 3
    sample_ids:
  PGexplainer:
    enabled: False
    number_of_samples: 3
    sample_ids:
  GNNexplainer:
    enabled: False
    number_of_samples: 3
    sample_ids:
  CFExplainer:
    enabled: False
    number_of_samples: 3
    sample_ids:
  ZORRO:
    enabled: True
    number_of_samples: 3
    sample_ids:
metrics:
  fidelity:
    enabled: True
    importance_range: 0.5,1
    importance_prop: 0.25
  contrastivity:
    enabled: True
    importance_range: 0.5,1
    importance_prop: 0.25
  sparsity:
    enabled: True
    importance_range: 0.5,1
    importance_prop: 0.5
custom_visualisation_options:
  GNN_models:
    DiffPool:
      cluster_nodes: True
  dataset:
    MUTAG:
      custom_mapping: {"0": "C","1": "N","2": "O","3": "F","4": "I","5": "Cl","6": "Br"}